curl 'http://localhost:3001/fodder-pools/ef6cd6e5-237a-43ab-8506-174b9db236dc/items' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'DNT: 1' \
  -H 'Origin: http://localhost:3000' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:3000/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoiZjRjMzYzY2ItZGNiNC00MTY1LWI2YTQtZWMxZmZhOGIxNTQ4Iiwicm9sZXMiOlsiYWRtaW46ZXhhbXMiLCJhZG1pbjp1c2VycyIsInVzZXIiLCJwdWJsaWMiXSwiaWF0IjoxNzM1ODg0MTQyLCJleHAiOjE3MzU4ODc3NDJ9.pqAGV-rvSVLY6hGGXIRil21TVKCDqSKMIPMNZbkQeSo' \
  -H 'content-type: application/json' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --data-raw '["ONe","TWo"]'